website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    flash("Please login to your account")
    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import current_app,url_for,redirect
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user,logout_user
from flask_login import UserMixin, login_user, LoginManager, login_required, logout_user, current_user
from flask import send_file, send_from_directory
from .models import Note, Track, User
from . import db
import json
from flask_uploads import UploadSet, configure_uploads, AUDIO, UploadNotAllowed
from flask import Flask, render_template, request
from flask_sqlalchemy import SQLAlchemy
from .script import TrackInfo
import os
from bs4 import BeautifulSoup
from sqlalchemy import create_engine
views = Blueprint('views', __name__)

@views.route('/', methods = ['GET','POST'])
@login_required
def home():
    tracks = Track.query.filter_by(user_id=current_user.id).all()
    Notes = Note.query.filter_by(user_id=current_user.id).all()
    return render_template("dash.html",tracks=tracks, Notes = Notes, user=current_user,countTracks = len(tracks), countNotes = len(Notes))


@views.route('/note', methods=['GET', 'POST'])
@login_required
def notes():
    if request.method == 'POST': 
        note = request.form.get('note')#Gets the note from the HTML 

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)  #providing the schema for the note 
            db.session.add(new_note) #adding the note to the database 
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("notes.html", user=current_user)



@views.route('/delete_note/<string:idd>', methods=['POST'])
@login_required
def delete_note(idd):  
    # print(1)
    
    noteId = idd
    note = Note.query.filter_by(id = noteId, user_id=current_user.id).first()

    if note:
        db.session.delete(note)
        db.session.commit()
        flash("Note successfully deleted",'success')
    else:
        flash("Unable to find the note")
    notes = Note.query.filter_by(user_id=current_user.id).all()
    return render_template("notes.html", notes=notes, user=current_user)



@views.route("/listen", methods=["GET"])
@login_required
def listen():
    tracks = Track.query.all()
    return render_template("listen.html",tracks=tracks,user=current_user)


audio = UploadSet("audio", AUDIO)

sep = os.path.sep
path = os.getcwd() + os.path.join(sep, "website"+sep+"static" + sep, "songs")
# C:\Users\mayan\OneDrive\Desktop\AuthFlask\Music-APP-\website\static\songs\Songs.PK_Unchained_Melodies_Encore_-_03_-_Ya_Rabba_Salaam-E-Ishq_1.mp3
@views.route("/update", methods=["GET", "POST"])
def update():
    
    if request.method == "POST" and "audio" in request.files:
        try:
            filename = audio.save(request.files["audio"])
            
            uploaded_track_path = filename
            song_lang = request.form["song_lang"]
            if filename and uploaded_track_path:
                print(path + sep + uploaded_track_path)
                track_info = TrackInfo.All(path + sep + uploaded_track_path)
                artist = track_info["artist"]
                if artist == None:
                    artist = "Unknown artist"
                title = track_info["title"]
                if title == None:
                    title = "Unknown track"
                if song_lang == None:
                    song_lang = "Not Defined"
                duration = track_info["track_lenght"]
                new_track = Track(
                    track_title=title,
                    track_artist=artist,
                    track_location=uploaded_track_path,
                    track_duration=duration,
                    track_language = song_lang,
                    user_id=current_user.id
                )
                db.session.add(new_track)
                db.session.commit()
            else:
                # else block to handle weird thing flask-uploads does, if any errors occur remove the file
                file = path + sep + uploaded_track_path
                os.remove(file)

            flash(filename + " " + "has been added to the library")
            tracks = Track.query.filter_by(user_id=current_user.id).all()
            Notes = Note.query.filter_by(user_id=current_user.id).all()
            return render_template("dash.html",tracks=tracks, Notes = Notes, user=current_user,countTracks = len(tracks), countNotes = len(Notes))

        except UploadNotAllowed as err:

            return "<h1>sorry file type is not allowed :( </h1>", 406

    return render_template("upload.html", user=current_user)


#Live Search for all the songs
@views.route('/search',methods=['GET','POST'])
@login_required
def search():
    tracks = Track.query.filter_by(user_id=current_user.id)
    return render_template("search.html",tracks=tracks, user=current_user)

#open the specific song
@views.route('/search/<string:idd>',methods=['GET','POST'])
@login_required
def ytsearch(idd):
    tracks = Track.query.filter_by(track_title=idd,user_id=current_user.id).all()
    return render_template("song.html", tracks = tracks, user=current_user)

#language map
@views.route('/search/language/<string:lang>',methods=['GET','POST'])
@login_required
def langsearch(lang):
    flash(f'Enjoy listening to your favourite {lang} songs')
    tracks = Track.query.filter_by(track_language = lang,user_id=current_user.id).all()
    return render_template("song.html", tracks = tracks, user=current_user)

# @views.route('/ytsearch/<string:song>',methods=['GET','POST'])   
# def ytSearch(idd):
# 	string=""
# 	song=idd
# 	song_name=song +'.mp3'
#     # print(song_name)
#     tracks = Track.query.filter_by(track_title=song, user_id=current_user.id).first()
# 	# cur=db.connection.cursor()
    
# 	# # result=cur.execute("SELECT * FROM songs_list WHERE song_name=%s",[song_name])
# 	# # albu69=cur.fetchall()
#     # tracks = Track.query.all()
# 	# if result>0:
# 	# 	return render_template('search.html',albu=albu69)
# 	# else:
# 	# 	try:
# 	# 		page = request.get("https://www.youtube.com/results?search_query="+song)
# 	# 		soup = BeautifulSoup(page.text,'html.parser')
# 	# 		for div in soup.find_all('div', { "class" : "yt-lockup-video" }):
# 	# 			if div.get("data-context-item-id") != None:
# 	# 				video_id = div.get("data-context-item-id")
# 	# 				break
# 	# 		os.system('youtube-dl --extract-audio --audio-format mp3 -o "akhil.mp3" https://www.youtube.com/watch?v='+video_id)
# 	# 		os.system("mv *.mp3 ./static/music/")
# 	# 		os.rename("static/music/akhil.mp3","static/music/"+song_name)
# 	# 		string="/static/music/"+song_name
# 	# 		cur=db.connection.cursor()
# 	# 		cur.execute("INSERT INTO songs_list(path,album,song_name) VALUES (%s,%s,%s)",(string,"NA",song_name))
# 	# 		db.connection.commit()
# 	# 		result=cur.execute("SELECT * FROM songs_list WHERE song_name=%s",[song_name])
# 	# 		albu99=cur.fetchall()
# 	# 		return render_template('search.html',albu=albu99)
        
# 	# 	except NameError:
# 	# 		flash('Song Not Found','success')
# 	# 		return render_template('home.html')

@views.route('/share/<string:idd>/user/<string:uid>', methods=["GET","POST"])
def shareUser(idd,uid):
    tracks = Track.query.filter_by(track_title = idd,user_id = uid).all()
    user = User.query.filter_by(id=uid).first()
    flash(f'Shared by {user.first_name}' )
    return render_template('Extview.html',tracks = tracks)

#Share the song with your friends
@views.route('/share/<string:idd>', methods=["GET","POST"])
@login_required
def share(idd):
    flash(f'Share your song with the link -> \"http://mayankgupta.pythonanywhere.com/share/{idd}/user/{current_user.id}\"')
	   
    return render_template('song.html', user = current_user)
sep = os.path.sep
path = os.getcwd() + os.path.join(sep, "website"+sep+"static" + sep, "songs")

# Download
@views.route('/download', methods=["GET","POST"])
@login_required
def download():
    if request.method == "POST":
        co = request.form['download']
        try:
            return send_file(path+sep+co, as_attachment=True)
        except Exception as e:
            return str(e)
        
#Map
@views.route('/map',methods=['GET','POST'])
@login_required
def map():
    tracks = Track.query.filter_by(user_id=current_user.id).all
    return render_template("map.html",tracks=tracks, user=current_user)

#profile
@views.route('/profile',methods=['GET','POST'])
@login_required
def profile():
    tracks = Track.query.filter_by(user_id=current_user.id).all()
    Notes = Note.query.filter_by(user_id=current_user.id).all()
    return render_template("dash.html",tracks=tracks, Notes = Notes, user=current_user,countTracks = len(tracks), countNotes = len(Notes))

#profile update
@views.route('/profile-update', methods=['GET','POST'])
@login_required
def profile_update():
    if request.method =='POST':
        newName = request.form.get('name')
        newEmail = request.form.get('email')
        if newName:
            current_user.first_name = newName
        if newEmail:
            current_user.email = newEmail
        db.session.commit()
    tracks = Track.query.filter_by(user_id=current_user.id).all()
    Notes = Note.query.filter_by(user_id=current_user.id).all()
    return render_template("dash.html",tracks=tracks, Notes = Notes, user=current_user,countTracks = len(tracks), countNotes = len(Notes))

@views.route('/delete_playlist/<string:idd>',methods=['GET','POST'])
@login_required
def delete_playlist(idd):
    tracks = Track.query.filter_by(track_title=idd,user_id=current_user.id).first()
    if tracks.user_id == current_user.id:
            db.session.delete(tracks)
            db.session.commit()
            flash("Playlist successfully deleted",'success')
            tracks = Track.query.filter_by(user_id=current_user.id).all()
            return render_template("song.html", tracks = tracks, user=current_user)
    

website/templates/Extview.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" type="text/css" href="{{url_for('static',
    filename='css/bootstrap.css') }}"">
    <link
      rel="stylesheet"
      type="text/css"
      href="{{url_for('static', filename='css/blocks.min.css') }}"
    />
    <style>
        body {
    
            background-image: url("{{url_for('static', filename='images/album-art.jpg')}}");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
          }
          </style>
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          <a class="nav-item nav-link" id="listen" href="/login">Listen</a>
          
                 
        </div>
      </div>
      
          
    </nav>
    {% for song in tracks %}
    <h1 style="color:gold; text-align: center;">Enjoy listen to "{{song.track_title}}" </h1> 
    <div class="card-deck" >
      <div class="card">
                    
        <div class="card-body block" style="width:98%; height:21em;">
          
          
          <p style="text-align: center;">
            Track: {{song.track_title}}<br>
            Artist: {{song.track_artist}}<br>
            Language: {{song.track_language}}<br>
            Duration: {{song.track_duration}}
            
          </p>
          <div class="container">
            <audio controls class="card-text">
              
                <source class="block" src="{{url_for('static', filename='songs/' + song.track_location) }}">  
              
            </audio>
          <div style="text-align: top-right;">
            <p><a href="/logout" class="navbar-form navbar-right">Login</a></p>
          </div>  
            <form action="/download" class="navbar-form navbar-left" method="POST">
              <br>
              <div class="filen"><button type="submit" name="download" value={{song.track_location}} id="download" class="btn btn-primary">DOWNLOAD</button></div>
            </form>
            <br>
            
            
            
          </div>
      
        </div>
      
      </div>
      <img src="{{ url_for('static', filename='images/art-album.jpg')}}" width="200" align="right">
      
    </div>

   


    {% endfor %}    


    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>


  </body>
</html>
    

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          <a class="nav-item nav-link" id="update" href="/update">Upload</a>
          <a class="nav-item nav-link" id="map" href="/map">Map</a>
          <a class="nav-item nav-link" id="search" href="/search">Search Song</a>
          <a class="nav-item nav-link" id="note" href="/note">Notes</a>    
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          <a class="nav-item nav-link" id="listen" href="/login">Listen</a>
          {% endif %}
          
        
        </div>
      </div>
      {% if user.is_authenticated %}
        <div float="right" align="right" color="white"><a href="/profile">Welcome {{user.first_name}}</a>  </div>
      {% else %}
        <div float="right" align="right" color="white"><a href="/login">Welcome {{user.first_name}}</a>  </div>
      {% endif %}
          
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>


  </body>
</html>

website/templates/dash.html
{% extends "base.html" %} {% block title %}Profile View{% endblock %} 
    {% block content %}

	<style>
		body {

			background-image: url("{{url_for('static', filename='images/disco2.jpg')}}");
			background-repeat: no-repeat;
			background-attachment: fixed;
			background-size: 100% 100%;
		}
	</style>
    <strong><h1 style="color: whitesmoke;">Welcome {{user.first_name}} </h1></strong>



	<bold><h2 align="center" style="color: white;">Dashboard</h2></bold>
	<br/>

	<div class="card">
  <div class="card-header">
    {{ current_user.first_name }}
  </div>
  <div class="card-body">
   
    <p class="card-text">

<div class="container">
	<div class="row">
		<div class="col-8">

    <strong>Name:</strong>
	{{ current_user.first_name }}<br/>

	<strong>Mobile Number:</strong>
	{{ current_user.username }}<br/>

	<strong>User Id:</strong>
	{{ current_user.id }}<br/>

	<strong>Email:</strong>
	{{ current_user.email }}<br/>

	<strong>Number of Songs Uploaded :</strong>
	{{ countTracks }} Tracks <br/>

	<strong>Number of Notes Added :</strong>
	{{ countNotes }} Notes <br/>




	
	

    	
    </p>
    <a href="{{ url_for('auth.logout')}}" class="btn btn-secondary btn-sm">Logout</a>

    <br/><br/>

    
	</div>
	<div class="col-4">
		{% if current_user.profile_pic %}

		<img src="{{ url_for('static', filename='images/' + current_user.profile_pic)}}" width="200" align="right">
		
		{% else %}

		<img src="{{ url_for('static', filename='images/headbook.avif')}}" width="350" align="right">

		{% endif %}
	
	</div>
	</div>
	</div>


  </div>
</div>
	

	
<br/>

<div class="card">
  <div class="card-header">
    Update Profile
  </div>
  <div class="card-body">

  	<form action="/profile-update" method="POST" enctype="multipart/form-data">
		<label for="name">Enter the name : </label>
        <input type="text" id="name" class="name" name="name"><br><br>

        <label for="email">Enter the email : </label>
        <input type="text" id="email" class="email" name="email"><br><br>

        <input type = "submit" value = "Update Profile">
	</form>



</div>

	
	


</div>


{% endblock %} 

website/templates/dashboard.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 
    {% block content %}
    <h1>Welcome {{user.first_name}} </h1>

<div class="container">
  <a href="/create_playlist" class="btn btn-info" role="button">Create public playlist</a>
  <a href="/create_private_playlist" class="btn btn-info" role="button">Create private playlist</a>
</div>
<hr>
<table class="table table-stripped table-hover">
	<tr>
		<th>PLAYLIST NAME</th>
		<th></th>
	</tr>
	{% for song in user.tracks %}
	<tr>
		<td><a href="play_playlist/{{song.id}}"  class="btn btn-default">{{song.title}}</a></td>

		<td></td>
		<td><a href="play_playlist/{{song.id}}" class="btn btn-default pull-right">PLAY</a></td>
		<td><a href="/Albums" class="btn btn-danger pull-right ">Add</a></td>
		<td><a href="delete_playlist/{{song.id}}" class="btn btn-default pull-right">DELETE</a></td>
		<td></td>
	</tr>
	{% endfor %}
</table>
    {% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 
    {% block content %}
    <h1>Welcome {{user.first_name}} </h1>

<div class="container">
  <a href="/create_playlist" class="btn btn-info" role="button">Create public playlist</a>
  <a href="/create_private_playlist" class="btn btn-info" role="button">Create private playlist</a>
</div>
<hr>
<table class="table table-stripped table-hover">
	<tr>
		<th>PLAYLIST NAME</th>
		<th></th>
	</tr>
	{% for song in user.tracks %}
	<tr>
		<td><a href="play_playlist/{{song.id}}"  class="btn btn-default">{{song.title}}</a></td>

		<td></td>
		<td><a href="play_playlist/{{song.id}}" class="btn btn-default pull-right">PLAY</a></td>
		<td><a href="/Albums" class="btn btn-danger pull-right ">Add</a></td>
		<td><a href="delete_playlist/{{song.id}}" class="btn btn-default pull-right">DELETE</a></td>
		<td></td>
	</tr>
	{% endfor %}
</table>
    {% endblock %}

website/templates/listen.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}
    <h1>Welcome {{user.first_name}} </h1> 
<html>
  <head>
    <title>listen</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static',
    filename='css/bootstrap.css') }}"">
    <link
      rel="stylesheet"
      type="text/css"
      href="{{url_for('static', filename='css/blocks.min.css') }}"
    />
    <meta name="viewport" content="width=device-width", initial-scale=1.0"/>
  </head>
  <body style="background-color: white;">
    {% for song in user.tracks %}

    <div class="card-deck">
      <div class="card">
        
              
        <div class="card-body block" style="width:40%; height:15em;">
          <!-- <img
          src="{{url_for('static', filename='images/album-art.jpg')}}"
          class="card-img-top"
          alt="art"
          /> -->
          <p style="text-align: center;">
            track: <a href="/search/{{song.track_title}}">{{song.track_title}}</a>
          </p>
          <div class="container">
            <audio controls class="card-text">
              
                <source class="block" src="{{url_for('static', filename='songs/' + song.track_location) }}">  
              
            </audio>
            
            <a href="/delete_playlist/{{song.track_title}}" class="btn btn-default pull-right">DELETE</a>
            
            <form action="/download" class="navbar-form navbar-left" method="POST">
              <br>
              <div class="filen"><button type="submit" name="download" value={{song.track_location}} id="download" class="btn btn-primary">DOWNLOAD</button></div>
            </form>
            <br>
            <form action="/share" class="navbar-form navbar-right" method="POST" >
              <div class="filen"><button type="submit" name="share" value={{song.track_title}} id="share" class="btn btn-primary">SHARE</button></div>
            </form>
            
          </div>
        </div>
      </div>
    </div>

   


    {% endfor %}    

  </body>
</html>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
    {% endblock %}

website/templates/upload.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 
{% block content %}
<!DOCTYPE html>
<html>
	<head>
		<title>Add some tunes</title>
		<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.css') }}"">
	</head>
	<body style="background-color: #343a40">
		<div class="card text-center" style="background-color: white">
			<form method=POST enctype=multipart/form-data action="{{ url_for('views.update') }}">
				<div class="card-header">
					<h1 class="h1" style="color:#007bff;">update your library</h1>
				</div>
				<div class="cutstom-file"><input type="file" name="audio" id="ent" class="btn btn-primary"></div>
				<br>
				<label for="song_lang">Please tell the language of song : </label>
				<input type="text" id="song_lang" class = "song_lang" name="song_lang" placeholder="Tamil/Punjabi..."><br>
				<br>
				<input class="btn btn-outline-dark" type="submit" id="sub">
				<div class="card-footer text-muted"></div>
			</form>
		</body>
	</html>
	{% endblock %}